### ISSUE TITLE
Include link to github page in description

### ISSUE THREAD

**Issue by hak8or** [nicocvn/cppreg#3]
Almost [all](https://github.com/containous/traefik) other [projects](https://github.com/mitmproxy/mitmproxy) include a [link](https://github.com/ARM-software/CMSIS_5) in their project description, I suggest we follow that route too since there is no other way to view the [github page](https://sendyne.github.io/cppreg/).

**Comment by sendyne-nicocvn** [comment]
Agreed and done.
